---
description: "#{repo}"
builds:
- platform: "linux"
  arch: "any"
  asset_filename: "#{repo}-#{version}-linux_amd64.tar.gz"
  sha_filename: "#{repo}-#{version}-sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
